// Reusable country codes for the entire application
export const countryCodes = [
  { id: "IN", country: "India", code: "IN" },
  { id: "US", country: "United States", code: "US" },
  { id: "GB", country: "United Kingdom", code: "GB" },
  { id: "CA", country: "Canada", code: "CA" },
  { id: "AU", country: "Australia", code: "AU" },
  { id: "DE", country: "Germany", code: "DE" },
  { id: "FR", country: "France", code: "FR" },
  { id: "JP", country: "Japan", code: "JP" },
  { id: "CN", country: "China", code: "CN" },
  { id: "BR", country: "Brazil", code: "BR" },
  { id: "MX", country: "Mexico", code: "MX" },
  { id: "IT", country: "Italy", code: "IT" },
  { id: "ES", country: "Spain", code: "ES" },
  { id: "RU", country: "Russia", code: "RU" },
  { id: "KR", country: "South Korea", code: "KR" },
  { id: "NL", country: "Netherlands", code: "NL" },
  { id: "SE", country: "Sweden", code: "SE" },
  { id: "NO", country: "Norway", code: "NO" },
  { id: "DK", country: "Denmark", code: "DK" },
  { id: "FI", country: "Finland", code: "FI" },
  { id: "CH", country: "Switzerland", code: "CH" },
  { id: "AT", country: "Austria", code: "AT" },
  { id: "BE", country: "Belgium", code: "BE" },
  { id: "IE", country: "Ireland", code: "IE" },
  { id: "PT", country: "Portugal", code: "PT" },
  { id: "GR", country: "Greece", code: "GR" },
  { id: "PL", country: "Poland", code: "PL" },
  { id: "CZ", country: "Czech Republic", code: "CZ" },
  { id: "HU", country: "Hungary", code: "HU" },
  { id: "RO", country: "Romania", code: "RO" },
  { id: "BG", country: "Bulgaria", code: "BG" },
  { id: "HR", country: "Croatia", code: "HR" },
  { id: "SI", country: "Slovenia", code: "SI" },
  { id: "SK", country: "Slovakia", code: "SK" },
  { id: "LT", country: "Lithuania", code: "LT" },
  { id: "LV", country: "Latvia", code: "LV" },
  { id: "EE", country: "Estonia", code: "EE" },
  { id: "IS", country: "Iceland", code: "IS" },
  { id: "MT", country: "Malta", code: "MT" },
  { id: "CY", country: "Cyprus", code: "CY" },
  { id: "LU", country: "Luxembourg", code: "LU" },
  { id: "NZ", country: "New Zealand", code: "NZ" },
  { id: "SG", country: "Singapore", code: "SG" },
  { id: "MY", country: "Malaysia", code: "MY" },
  { id: "TH", country: "Thailand", code: "TH" },
  { id: "PH", country: "Philippines", code: "PH" },
  { id: "ID", country: "Indonesia", code: "ID" },
  { id: "VN", country: "Vietnam", code: "VN" },
  { id: "BD", country: "Bangladesh", code: "BD" },
  { id: "PK", country: "Pakistan", code: "PK" },
  { id: "LK", country: "Sri Lanka", code: "LK" },
  { id: "MM", country: "Myanmar", code: "MM" },
  { id: "KH", country: "Cambodia", code: "KH" },
  { id: "LA", country: "Laos", code: "LA" },
  { id: "BT", country: "Bhutan", code: "BT" },
  { id: "MV", country: "Maldives", code: "MV" },
  { id: "NP", country: "Nepal", code: "NP" },
  { id: "AF", country: "Afghanistan", code: "AF" },
  { id: "AE", country: "United Arab Emirates", code: "AE" },
  { id: "SA", country: "Saudi Arabia", code: "SA" },
  { id: "QA", country: "Qatar", code: "QA" },
  { id: "KW", country: "Kuwait", code: "KW" },
  { id: "BH", country: "Bahrain", code: "BH" },
  { id: "OM", country: "Oman", code: "OM" },
  { id: "JO", country: "Jordan", code: "JO" },
  { id: "IL", country: "Israel", code: "IL" },
  { id: "LB", country: "Lebanon", code: "LB" },
  { id: "SY", country: "Syria", code: "SY" },
  { id: "IQ", country: "Iraq", code: "IQ" },
  { id: "IR", country: "Iran", code: "IR" },
  { id: "TR", country: "Turkey", code: "TR" },
  { id: "EG", country: "Egypt", code: "EG" },
  { id: "ZA", country: "South Africa", code: "ZA" },
  { id: "NG", country: "Nigeria", code: "NG" },
  { id: "KE", country: "Kenya", code: "KE" },
  { id: "GH", country: "Ghana", code: "GH" },
  { id: "UG", country: "Uganda", code: "UG" },
  { id: "TZ", country: "Tanzania", code: "TZ" },
  { id: "ET", country: "Ethiopia", code: "ET" },
  { id: "MA", country: "Morocco", code: "MA" },
  { id: "DZ", country: "Algeria", code: "DZ" },
  { id: "TN", country: "Tunisia", code: "TN" },
  { id: "LY", country: "Libya", code: "LY" },
  { id: "SD", country: "Sudan", code: "SD" },
  { id: "AR", country: "Argentina", code: "AR" },
  { id: "CL", country: "Chile", code: "CL" },
  { id: "CO", country: "Colombia", code: "CO" },
  { id: "PE", country: "Peru", code: "PE" },
  { id: "VE", country: "Venezuela", code: "VE" },
  { id: "EC", country: "Ecuador", code: "EC" },
  { id: "BO", country: "Bolivia", code: "BO" },
  { id: "PY", country: "Paraguay", code: "PY" },
  { id: "UY", country: "Uruguay", code: "UY" },
  { id: "GY", country: "Guyana", code: "GY" },
  { id: "SR", country: "Suriname", code: "SR" },
  { id: "GF", country: "French Guiana", code: "GF" }
];

// City codes for common cities (mock data as requested)
export const cityCodes = [
  { id: "BNG", name: "Bangalore", country: "IN" },
  { id: "DEL", name: "Delhi", country: "IN" },
  { id: "MUM", name: "Mumbai", country: "IN" },
  { id: "CHE", name: "Chennai", country: "IN" },
  { id: "HYD", name: "Hyderabad", country: "IN" },
  { id: "KOL", name: "Kolkata", country: "IN" },
  { id: "PUN", name: "Pune", country: "IN" },
  { id: "AHM", name: "Ahmedabad", country: "IN" },
  { id: "JAI", name: "Jaipur", country: "IN" },
  { id: "SUR", name: "Surat", country: "IN" },
  { id: "NYC", name: "New York City", country: "US" },
  { id: "LAX", name: "Los Angeles", country: "US" },
  { id: "CHI", name: "Chicago", country: "US" },
  { id: "HOU", name: "Houston", country: "US" },
  { id: "PHX", name: "Phoenix", country: "US" },
  { id: "PHI", name: "Philadelphia", country: "US" },
  { id: "SAN", name: "San Antonio", country: "US" },
  { id: "DAL", name: "Dallas", country: "US" },
  { id: "SJO", name: "San Jose", country: "US" },
  { id: "AUS", name: "Austin", country: "US" },
  { id: "LON", name: "London", country: "GB" },
  { id: "BIR", name: "Birmingham", country: "GB" },
  { id: "MAN", name: "Manchester", country: "GB" },
  { id: "GLW", name: "Glasgow", country: "GB" },
  { id: "LIV", name: "Liverpool", country: "GB" },
  { id: "TOR", name: "Toronto", country: "CA" },
  { id: "VAN", name: "Vancouver", country: "CA" },
  { id: "MON", name: "Montreal", country: "CA" },
  { id: "CAL", name: "Calgary", country: "CA" },
  { id: "EDM", name: "Edmonton", country: "CA" },
  { id: "SYD", name: "Sydney", country: "AU" },
  { id: "MEL", name: "Melbourne", country: "AU" },
  { id: "BRI", name: "Brisbane", country: "AU" },
  { id: "PER", name: "Perth", country: "AU" },
  { id: "ADE", name: "Adelaide", country: "AU" }
];